udo: required
services:
  - docker

before_install:
  - docker build -t devstbz/dockjango-test-app .
  - docker build -t devstbz/dockjango-nginx-app ./nginx

script:
  - docker images 


after_success:
  - docker build -t devstbz/dockjango-test-app .
  - docker build -t devstbz/dockjango-nginx-app ./nginx

  # Log into the docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push devstbz/dockjango-test-app
  - docker push devstbz/dockjango-nginx-app



deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "dockjango-docker"
  env: "DockjangoDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-323216669271"
  bucket_path: "dockjango-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY
