udo: required
services:
  - docker

before_install:
  - docker build -t devstbz/dockjango-test-app .

script:
  - docker images

after_success:
  - docker build -t devstbz/dockjango-test-app .

  # Log into the docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push devstbz/dockjango-test-app




deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: dockjango-docker
  env: DockjangoDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-323216669271
  bucket_path: dockjango-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY
