version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
